definitions:
  entity.User:
    properties:
      createdAt:
        example: "2021-10-24T00:12:39.469332+09:00"
        type: string
      email:
        example: foo@example.com
        type: string
      id:
        type: integer
      name:
        example: Taro Yamada
        type: string
      updatedAt:
        example: "2021-10-24T00:12:39.469332+09:00"
        type: string
    type: object
info:
  contact: {}
  description: This is a practice.
  title: go-mux-gorm
  version: "0.1"
paths:
  /users/{id}:
    get:
      description: ユーザ一覧を返却する
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/entity.User'
      summary: ユーザ一覧
swagger: "2.0"
